import type { Marker } from "./types";

// Mock dataset for markers - to be replaced with database later
export const mockMarkers: Marker[] = [
  // Berlin markers
  {
    id: "1",
    title: "Bohrmaschine zum Ausleihen",
    description: "Profi-Bohrmaschine mit Zubehör, guter Zustand",
    category: "sharing",
    lat: 52.52,
    lng: 13.405,
    address: "Berlin Mitte",
    countryCode: "DE",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Hilfe beim Umzug gesucht",
    description: "Suche 2 Helfer für Samstag, 4h, 15€/h",
    category: "jobs",
    lat: 52.495,
    lng: 13.42,
    address: "Berlin Kreuzberg",
    countryCode: "DE",
    createdAt: "2024-01-16T14:30:00Z",
  },
  {
    id: "3",
    title: "Nachbarschafts-Flohmarkt",
    description: "Jährlicher Flohmarkt im Hinterhof, alle willkommen!",
    category: "events",
    lat: 52.54,
    lng: 13.39,
    address: "Berlin Prenzlauer Berg",
    countryCode: "DE",
    createdAt: "2024-01-17T09:00:00Z",
  },
  {
    id: "4",
    title: "Bücher tauschen",
    description: "Große Sammlung Romane gegen Sachbücher tauschen",
    category: "swap",
    lat: 52.51,
    lng: 13.45,
    address: "Berlin Friedrichshain",
    countryCode: "DE",
    createdAt: "2024-01-18T11:00:00Z",
  },
  {
    id: "5",
    title: "Gemüse aus dem Garten",
    description: "Frische Tomaten und Zucchini zu verschenken",
    category: "food",
    lat: 52.48,
    lng: 13.38,
    address: "Berlin Neukölln",
    countryCode: "DE",
    createdAt: "2024-01-19T08:00:00Z",
  },
  // Munich markers
  {
    id: "6",
    title: "Fahrrad-Reparatur Service",
    description: "Repariere Fahrräder in meiner Freizeit, faire Preise",
    category: "jobs",
    lat: 48.137,
    lng: 11.576,
    address: "München Zentrum",
    countryCode: "DE",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "7",
    title: "Camping-Ausrüstung verleihen",
    description: "Zelt, Schlafsäcke, Kochgeschirr für Wochenende",
    category: "sharing",
    lat: 48.145,
    lng: 11.56,
    address: "München Schwabing",
    countryCode: "DE",
    createdAt: "2024-01-21T15:00:00Z",
  },
  // Hamburg markers
  {
    id: "8",
    title: "Yoga im Park",
    description: "Kostenloses Yoga jeden Sonntag um 10 Uhr",
    category: "events",
    lat: 53.551,
    lng: 9.993,
    address: "Hamburg Altstadt",
    countryCode: "DE",
    createdAt: "2024-01-22T10:00:00Z",
  },
  {
    id: "9",
    title: "Kinderspielzeug tauschen",
    description: "Gut erhaltene Spielsachen für Kleinkinder",
    category: "swap",
    lat: 53.56,
    lng: 10.0,
    address: "Hamburg St. Georg",
    countryCode: "DE",
    createdAt: "2024-01-23T14:00:00Z",
  },
  // International markers
  {
    id: "10",
    title: "Community Garden Day",
    description: "Join us for planting and gardening activities",
    category: "events",
    lat: 51.507,
    lng: -0.127,
    address: "London, Westminster",
    countryCode: "UK",
    createdAt: "2024-01-24T09:00:00Z",
  },
  {
    id: "11",
    title: "Tool Library",
    description: "Borrow tools for your DIY projects",
    category: "sharing",
    lat: 48.856,
    lng: 2.352,
    address: "Paris, 4th arrondissement",
    countryCode: "FR",
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: "12",
    title: "Language Exchange Meetup",
    description: "Practice languages with native speakers",
    category: "events",
    lat: 40.713,
    lng: -74.006,
    address: "New York, Manhattan",
    countryCode: "US",
    createdAt: "2024-01-26T18:00:00Z",
  },
];
